apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc-data.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: sonustemper-proxy
    files:
      - proxy-entrypoint.sh
      - nginx.conf.template

generatorOptions:
  disableNameSuffixHash: true
