apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonustemper-data
  labels:
    app.kubernetes.io/name: sonustemper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
