apiVersion: v1
kind: Secret
metadata:
  name: sonustemper-auth
  labels:
    app.kubernetes.io/name: sonustemper
type: Opaque
stringData:
  basic-auth-pass: CHANGEME
  proxy-shared-secret: changeme-proxy
